# This config file perturbs the parameter UnempC over 21 values between -0.65 and -2.65.

UnempC_n0.650:
    UnempC: -0.650

UnempC_n0.750:
    UnempC: -0.750

UnempC_n0.850:
    UnempC: -0.850

UnempC_n0.950:
    UnempC: -0.950

UnempC_n1.050:
    UnempC: -1.050

UnempC_n1.150:
    UnempC: -1.150

UnempC_n1.250:
    UnempC: -1.250

UnempC_n1.350:
    UnempC: -1.350

UnempC_n1.450:
    UnempC: -1.450

UnempC_n1.550:
    UnempC: -1.550

UnempC_n1.650:
    UnempC: -1.650

UnempC_n1.750:
    UnempC: -1.750

UnempC_n1.850:
    UnempC: -1.850

UnempC_n1.950:
    UnempC: -1.950

UnempC_n2.050:
    UnempC: -2.050

UnempC_n2.150:
    UnempC: -2.150

UnempC_n2.250:
    UnempC: -2.250

UnempC_n2.350:
    UnempC: -2.350

UnempC_n2.450:
    UnempC: -2.450

UnempC_n2.550:
    UnempC: -2.550

UnempC_n2.650:
    UnempC: -2.650
