# This config file perturbs the parameter UnempD over 21 values between -0.15 and -2.15.

UnempD_n0.150:
    UnempD: -0.150

UnempD_n0.250:
    UnempD: -0.250

UnempD_n0.350:
    UnempD: -0.350

UnempD_n0.450:
    UnempD: -0.450

UnempD_n0.550:
    UnempD: -0.550

UnempD_n0.650:
    UnempD: -0.650

UnempD_n0.750:
    UnempD: -0.750

UnempD_n0.850:
    UnempD: -0.850

UnempD_n0.950:
    UnempD: -0.950

UnempD_n1.050:
    UnempD: -1.050

UnempD_n1.150:
    UnempD: -1.150

UnempD_n1.250:
    UnempD: -1.250

UnempD_n1.350:
    UnempD: -1.350

UnempD_n1.450:
    UnempD: -1.450

UnempD_n1.550:
    UnempD: -1.550

UnempD_n1.650:
    UnempD: -1.650

UnempD_n1.750:
    UnempD: -1.750

UnempD_n1.850:
    UnempD: -1.850

UnempD_n1.950:
    UnempD: -1.950

UnempD_n2.050:
    UnempD: -2.050

UnempD_n2.150:
    UnempD: -2.150
