# This config file perturbs the parameter UnempH over 21 values between -0.3 and -2.3.

UnempH_n0.300:
    UnempH: -0.300

UnempH_n0.400:
    UnempH: -0.400

UnempH_n0.500:
    UnempH: -0.500

UnempH_n0.600:
    UnempH: -0.600

UnempH_n0.700:
    UnempH: -0.700

UnempH_n0.800:
    UnempH: -0.800

UnempH_n0.900:
    UnempH: -0.900

UnempH_n1.000:
    UnempH: -1.000

UnempH_n1.100:
    UnempH: -1.100

UnempH_n1.200:
    UnempH: -1.200

UnempH_n1.300:
    UnempH: -1.300

UnempH_n1.400:
    UnempH: -1.400

UnempH_n1.500:
    UnempH: -1.500

UnempH_n1.600:
    UnempH: -1.600

UnempH_n1.700:
    UnempH: -1.700

UnempH_n1.800:
    UnempH: -1.800

UnempH_n1.900:
    UnempH: -1.900

UnempH_n2.000:
    UnempH: -2.000

UnempH_n2.100:
    UnempH: -2.100

UnempH_n2.200:
    UnempH: -2.200

UnempH_n2.300:
    UnempH: -2.300
